spring:
  application:
    name: SpringAIDemo

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          temperature: 0.3
          num-predict: 2048
          model: mistral

    mcp:
      client:
        enabled: true
        request-timeout: 60s
        stdio:
          servers-configuration: classpath:/mcp-servers.json

        sse:
          connections:
            weather-countries-mcp:
              url: http://localhost:8081

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    com.boghdady: DEBUG
    org.springframework.ai: INFO
    org.springframework.ai.mcp: DEBUG

